### PR TITLE
Added __iter__ function to Song.py

### PR DESCRIPTION
**Pull request by mbramson**
Added an iterator function to Song.py to enable
easy iteration through song attributes.

Signed-off-by: Mathew Bramson <mathewbramson@gmail.com>

### CODE REVIEW

**Comment by liamks** [comment]
Excellent!!

**Comment by liamks** [comment]
Feel free to update the readme if want your name listed in the contributors section.

**Comment by mbramson** [comment]
Cool. I'm using pyItunes to port my iTunes data into a pandas dataframe. Probably outside the scope of pyitunes to have a dataframe function, but having a to dictionary function for the song item makes porting into pandas extremely easy. I've got an elegant one written, do you agree that soemthing like that fits the scope of the project? I'll post to my github fork tonight what I mean.

**Comment by liamks** [comment]
Very neat - the dictionary function will certainly be useful for others!

**Pull request merged**
