### PR TITLE
Update Song.py

### PR DESCRIPTION
**Pull request by AllanMarcus**
Added more attributes: track_type, podcast, movie, has_video

### CODE REVIEW

**Comment by liamks** [comment]
@AllanMarcus it looks like this has a merge conflict - is this a dup of one of your other PRs?

**Comment by AllanMarcus** [comment]
it might. Sorry for the delay, I was away from a computer for a while. I will look at it tonight.

**Comment by AllanMarcus** [comment]
Some lines are probably duplicated. I'm new to git and I don't know how to resolve it. Sorry, I should have been more careful.

**Comment by liamks** [comment]
I'm going to close this PR. If you'd like to create a new one with the updates that weren't part of the other PRs let me know! Cheers!

**Pull request closed without merging**
