### PR TITLE
Added test library and basic tests.

### PR DESCRIPTION
**Pull request by NathanDotTo**
Please have a look at these basic tests.

### CODE REVIEW

**Comment by shacker** [comment]
Nice! I can't easily tell - does the sample xml have an example of nested playlists? (because we'll probably want to test for that at some point). 

Suggestion: You're running multiple tests in one test, and they should be separated. I would create a  [def setUp()](https://docs.djangoproject.com/en/1.11/topics/testing/overview/) at the top of the class, then in the two loops you can use `self.it_library.songs.items()` and `self.it_library.getPlaylist(playlists[0]).tracks` respectively. Then we'll have reusability of the loaded library for all of the tests to come.

**Comment by NathanDotTo** [comment]
Cool, let me make those changes and update the pull request please.

I don’t think I have nested playlists, but that is a good idea. It is fiddly getting the sample library structure to work, which held me up.

Now something works at all, we can play some more.

**Comment by shacker** [comment]
Looks good to me, thanks. 

@liamks I thought you had mentioned that I now had merge privs, but I don't.

**Comment by liamks** [comment]
@shacker I believe you need to accept the invite first. Double check your spam just in case the invite slipped through. Maybe Github has a notification for the invite to collaborator?

**Comment by shacker** [comment]
Ah cool - I have Merge rights now. Thanks for the tests.

**Pull request merged**
